name: CI_CD_DEMO

on:
  push:
    branches: ["Deploy"]

jobs:
  pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v5

      - name: 🟢 Setup Node
        uses: actions/setup-node@v5
        with:
          node-version: 25

      - name: 📦 Install deps
        run: yarn install

      - name: 🎨 Prettier check
        run: yarn prettify

      - name: 🧪 Run tests
        run: yarn test

      - name: 🐳 Build Docker image
        run: docker build -t ci-cd-api .

      - name: 🚀 Run container
        run: docker run -d -p 3000:3000 ci-cd-api

      - name: ⏳ Wait for API
        run: npx wait-port 3000

      - name: 🌐 Test API
        run: curl http://localhost:3000/items